#マザーボード
#左上にI/Oポートが来るように設置した場合の左下を原点とする
#ATXマザーボード
ATX:
  X: 243.84
  Y: 304.8
  HOLE:
    - x: 10.16
      y: 16.51
    - x: 165.1
      y: 16.51
    - x: 237.49
      y: 16.51
    - x: 10.16
      y: 95.25
    - x: 10.16
      y: 140.97
    - x: 165.1
      y: 140.97
    - x: 237.49
      y: 140.97
    - x: 33.02
      y: 298.45
    - x: 165.1
      y: 298.45
    - x: 237.49
      y: 298.45
  HOLE_DIA: 4

#HDD SSD
#上にSATAコネクタが来るように設置した場合の左下を原点とする
#2.5インチSSD横置き
SATA2.5inc_H:
  X: 69.85
  Y: 100.45
  HOLE:
    - x: 4.065
      y: 9.85
    - x: 4.065
      y: 86.45
    - x: 65.785
      y: 9.85
    - x: 65.785
      y: 86.45
  HOLE_DIA: 4