#マザーボード
#左上にI/Oポートが来るように設置した場合の左下を原点とする
#ATXマザーボード
ATX:
  X: 243.84
  Y: 304.8
  HOLE:
    - x: 10.16
      y: 16.51
    - x: 165.1
      y: 16.51
    - x: 237.49
      y: 16.51
    - x: 10.16
      y: 95.25
    - x: 10.16
      y: 140.97
    - x: 165.1
      y: 140.97
    - x: 237.49
      y: 140.97
    - x: 33.02
      y: 298.45
    - x: 165.1
      y: 298.45
    - x: 237.49
      y: 298.45
  HOLE_DIA: 4

#HDD SSD
#上にSATAケーブルが来るように設置した場合の左下を原点とする
#2.5インチSSD
SSD2.5inc:
